language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libopenblas-dev
jobs:
  allow_failures:
    - rust: nightly
  include:
    # add a job to test the nightly features on the nightly build
    - rust: nightly
      script:
        - cargo +nightly build --verbose --features nightly
        - cargo +nightly test --verbose --features nightly
