language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
script:
  nightly:
    - cargo +nightly build --verbose --features nightly
    - cargo +nightly test --verbose --features nightly
