language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
# add a job to test the nightly features on the nightly build
jobs:
  allow_failures:
    - rust: nightly
  include:
    # - rust: stable
    # - rust: beta
    - rust: nightly
      script:
        - cargo +nightly build --verbose --features nightly
        - cargo +nightly test --verbose --features nightly
