language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libopenblas-dev
jobs:
  allow_failures:
    - rust: nightly
  # The nightly features have been stabilized, so there's no longer need for
  # additional tasks here.
  # include:
  #   - rust: nightly
  #     script:
  #       - cargo +nightly build --verbose --features nightly
  #       - cargo +nightly test --verbose --features nightly
