[package]
name = "ndarray-glm"
version = "0.0.2"
authors = ["Felix Clark <mfclark3690@gmail.com>"]
description = "Performs regression for general linear models on data stored in arrays using IRLS."
edition = "2018"
repository = "https://github.com/felix-clark/ndarray-glm"
readme = "README.md"
license = "MIT"
keywords = ["statistics", "glm", "irls"]
categories = ["mathematics", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
openblas = ["ndarray-linalg/openblas"]
# "openblas-src" implies "openblas"
openblas-src = ["ndarray-linalg/openblas-src"]
netlib = ["ndarray-linalg/netlib"]
intel-mkl = ["ndarray-linalg/intel-mkl"]

[dependencies]
# TODO: is rayon really needed? it should probably be a library feature
# ndarray = { version = "0.13", features = ["blas", "rayon"]}
ndarray = { version = "0.13", features = ["blas", "approx"] }
# perhaps the "openblas-src" feature should be reserved for a final crate?
ndarray-linalg = { version = "0.12" }
num-traits = "0.2"
thiserror = "1.0"
itertools = "0.8"

[dev-dependencies]
# pick a backend to run tests
blas-src = { version = "0.4", default-features = false, features = ["openblas"] }
ndarray-linalg = { version = "0.12", default-features = false, features = ["openblas-src"]}
anyhow = "1.0"
approx = "0.3"
# including openblas-src causes linking errors with LAPACKE?
# Include it as a feature to ndarray-linalg instead.
# https://github.com/blas-lapack-rs/openblas-src/issues/30
# openblas-src = { version = "0.7.0", default-features = false, features = ["cblas", "lapacke", "system"] }
