[package]
name = "irls"
version = "0.1.0"
authors = ["Felix Clark <mfclark3690@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.13", features = ["blas", "serde", "rayon"]}
# blas-src must depend on the same version as ndarray.
# blas-src = { version = "0.2", default-features = false, features = ["openblas"] }
# openblas-src = { version = "0.6.0", default-features = false, features = ["cblas", "system"] }
# maybe revert to the previous lines; the next version of ndarray should have these version numbers:
blas-src = { version = "0.4", default-features = false, features = ["openblas"] }
# openblas-src = { version = "0.7.0", default-features = false, features = ["cblas", "system"] }
# remove "system" to manually build openblas as suggested here:
# https://github.com/rust-ndarray/ndarray/issues/586
# the initial compilation takes a very long time so this isn't ideal, but is a workaround to linker errors.
openblas-src = { version = "0.7.0", default-features = false, features = ["cblas"] }
